const carData = [
  {
    name: "Toyota Corolla",
    brand: "Toyota",
    year: 2022,
    price: "$25,000",
    horsepower: 140,
    fuelEfficiency: "30 mpg",
  },
  {
    name: "Honda Civic",
    brand: "Honda",
    year: 2021,
    price: "$24,500",
    horsepower: 158,
    fuelEfficiency: "32 mpg",
  },
  {
    name: "Ford Mustang",
    brand: "Ford",
    year: 2022,
    price: "$35,000",
    horsepower: 310,
    fuelEfficiency: "25 mpg",
  },
  {
    name: "Chevrolet Silverado",
    brand: "Chevrolet",
    year: 2021,
    price: "$40,200",
    horsepower: 355,
    fuelEfficiency: "18 mpg",
  },
  {
    name: "Nissan Rogue",
    brand: "Nissan",
    year: 2022,
    price: "$28,800",
    horsepower: 170,
    fuelEfficiency: "29 mpg",
  },
  {
    name: "BMW 3 Series",
    brand: "BMW",
    year: 2021,
    price: "$42,000",
    horsepower: 255,
    fuelEfficiency: "27 mpg",
  },
  {
    name: "Chevrolet Silverado",
    brand: "Chevrolet",
    year: 2021,
    price: "$40,200",
    horsepower: 355,
    fuelEfficiency: "18 mpg",
  },
  {
    name: "Nissan Rogue",
    brand: "Nissan",
    year: 2022,
    price: "$28,800",
    horsepower: 170,
    fuelEfficiency: "29 mpg",
  },
  {
    name: "BMW 3 Series",
    brand: "BMW",
    year: 2021,
    price: "$42,000",
    horsepower: 255,
    fuelEfficiency: "27 mpg",
  },
  {
    name: "Chevrolet Silverado",
    brand: "Chevrolet",
    year: 2021,
    price: "$40,200",
    horsepower: 355,
    fuelEfficiency: "18 mpg",
  },
  {
    name: "Nissan Rogue",
    brand: "Nissan",
    year: 2022,
    price: "$28,800",
    horsepower: 170,
    fuelEfficiency: "29 mpg",
  },
  {
    name: "BMW 3 Series",
    brand: "BMW",
    year: 2021,
    price: "$42,000",
    horsepower: 255,
    fuelEfficiency: "27 mpg",
  },
  {
    name: "Chevrolet Silverado",
    brand: "Chevrolet",
    year: 2021,
    price: "$40,200",
    horsepower: 355,
    fuelEfficiency: "18 mpg",
  },
  {
    name: "Nissan Rogue",
    brand: "Nissan",
    year: 2022,
    price: "$28,800",
    horsepower: 170,
    fuelEfficiency: "29 mpg",
  },
  {
    name: "BMW 3 Series",
    brand: "BMW",
    year: 2021,
    price: "$42,000",
    horsepower: 255,
    fuelEfficiency: "27 mpg",
  },
];

export default carData;
